# Generated by Django 2.2 on 2020-04-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200429_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discounted_prices',
            new_name='discounted_price',
        ),
    ]
