# Generated by Django 2.2 on 2020-04-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200429_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='decription',
            field=models.TextField(null=True),
        ),
    ]
