# Generated by Django 2.2 on 2020-04-29 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_decription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='decription',
            new_name='description',
        ),
    ]
